version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  migrations:
    build: ../app/.
    env_file:
      - docker.env

    command: python manage.py migrate
    depends_on:
      - db
  app:
    build: ../app/.
    tty: true
    env_file:
      - docker.env
    ports:
      - "80:80"
    command: python manage.py runserver 0.0.0.0:80
    depends_on:
      - db
      - rabbitmq
      - migrations
    volumes:
      - ../app:/code/

  celery:
    build: ../app/.
    env_file:
      - docker.env
    command: celery -A myshop worker -l info
    depends_on:
      - db
      - rabbitmq
      - app

volumes:
  postgres_data:
  rabbitmq:
  redis_data: